## NDP Systèmes Odoo image version
## ref: https://hub.docker.com/r/bitnami/odoo/tags/
##
image:
  registry: docker.io
  repository: ndpsystemes/odoo
  tag: "10.0"
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always

## Set host, user and password to connect to the test database
postgresql:
  host:
  postgresUser:
  postgresPassword:

odoo:
  ## Override to define a custom module to install
  ## Default to "<RELEASE_NAME>_erp"
  installModule:
  ## Override here to define a custom database
  database:
  ## Set to "False" string to hav demo data loaded
  withoutDemo: "False"
  ## Additional command line params to send to odoo (string)
  cmdLineParams:
  ## Set to "True" string for testing Odoo
  testEnable: "True"
  ## Set to "True" string for stopping after DB initialization
  ## (Useful mainly for tests)
  stopAfterInit: "True"
  ## Regex for allowed databases
  dbFilter: ".*"
  ## Set to False if you do not want unaccentuated searches
  unaccent: "True"
  ## Set log level
  logLevel: "info"

git:
  ## Default server for repositories
  server: gitlab.ndp-systemes.fr
  ## Default branch for repositories
  branch:

  pullKeySecret:
    name: "ssh-private-key-deploy"
    key: "deploy_key_NDP"

  gitlabToken:
    name: "ssh-private-key-deploy"
    key: "gitlab_token"

  repositories:
    ## Add git repositories
    ## method: ssh or https. Defaults to ssh
    ## branch: branch name. Defaults to git.branch or image.tag
    ## server: git server name. Defaults to git.server. If set, https is assumed.
    ## httpsSecret: name of a secret with https credentials. Secret must contain a 'username' and a 'password'

    # DEPOT_GIT:
    #   path: my-user/my-project
    #   method: ssh
    #   server: github.com
    #   httpsCredentials: my-https-secret

# Define custom environment variables to pass to the image here
extraEnv: {}

# Define node affinity with the given release or leave empty for no affinity
affinityRelease:
