apiVersion: v1
kind: Service
metadata:
  name: {{ template "aeroodocs.name" . }}
  labels:
    app: {{ template "aeroodocs.name" . }}
    chart: {{ template "aeroodocs.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8989
    targetPort: http
  selector:
    app: {{ template "aeroodocs.name" . }}
    release: {{ .Release.Name }}
