apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "static-site.name" . }}
    chart: {{ template "static-site.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "static-site.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "static-site.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "static-site.name" . }}
        chart: {{ template "static-site.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
        - env:
          image: {{ template "static-site.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: {{ template "static-site.fullname" . }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
