{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "odoo.fullname" . }}
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ template "odoo.hostname" . }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "odoo.fullname" . }}
            servicePort: http
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}
---
{{- end }}
