apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "odoo.postgresql.fullname" . }}-initscripts
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  startup.sh: |
    #!/bin/bash
    export PGPASSWORD=$POSTGRES_PASSWORD
    echo "Creating user {{ .Values.postgresql.dbUser }}"
    psql -c "DROP USER IF EXISTS {{ .Values.postgresql.dbUser }}; CREATE USER {{ .Values.postgresql.dbUser }} WITH SUPERUSER PASSWORD '$(echo $POSTGRES_PASSWORD)';"
    echo "Checking if a dump must be loaded..."
    {{- if .Values.postgresql.dumpPath }}
    stat {{ .Values.postgresql.dumpPath }} > /dev/null || exit 0
    echo "Found a dump at {{ .Values.postgresql.dumpPath }} to load"
    echo "Creating {{ template "odoo.database" . }}"
    psql -c "DROP DATABASE IF EXISTS \"{{ template "odoo.database" . }}\";"
    psql -c "CREATE DATABASE \"{{ template "odoo.database" . }}\" WITH OWNER={{ .Values.postgresql.dbUser }};"
    pg_restore -d {{ template "odoo.database" . }} -v -O -U odoo {{ .Values.postgresql.dumpPath }} || true
    {{- end }}
