apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "odoo.postgresql.fullname" . }}-initscripts
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  permissions.sh: |
    #!/bin/bash
    psql -c "ALTER USER {{ .Values.postgresql.postgresqlUsername }} WITH Superuser;" -U postgres
